spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  application:
    name: clientApp

  main:
    allow-bean-definition-overriding: true


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

server:
  error:
    include-exception: true
    include-message: always